version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_app
    ports:
      - "8001:8000"   # Laravel's default port mapped to
      - "5173:5173"   # Vite port
    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}   # Make sure to set a key (run `php artisan key:generate`)
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      NODE_ENV: development
    volumes:
      - ./laravel:/app
    depends_on:
      - db
      - phpmyadmin

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
